auth_market/urls.py
from django.urls import path
from . import views
app_name = "auth_market"
urlpatterns = [
    path("login/", views.login_user, name="login_user"),
    path("log_out/", views.log_out, name = "log_out"),
    path('register/', views.register, name='register'),
    path("change_info/", views.change_info, name = "change_info"),
    path("change_username/", views.change_username, name = "change_username"),
    path("change_email/", views.change_email, name = "change_email"),
    path("send_secret_key/", views.send_secret_key, name = "send_secret_key"),
    path("display_user_account/", views.display_user_account, name = "display_user_account")
    ]

folder_market/urls.py
from django.urls import path
from . import views

app_name = "folder_market"
urlpatterns = [
    path("", views.RedirectIndex.as_view() , name="redirect_index"),
    path("<int:page>", views.Index.as_view(), name="index"),
    path("dashboard_items/", views.DashboardItems.as_view(), name="dashboard_items"),
    path("update_item/<str:check_item>/", views.UpdateItem.as_view(), name = "update_item"),
    path("dashboard_salesmans/", views.DashboardSalesmans.as_view(), name="dashboard_salesmans"),
    path("start_trade/", views.StartTrade.as_view(), name = "start_trade"),
    path("search/", views.SearchItem.as_view(), name= "search_item"),
    path("find_your_order/<int:id_product>/", views.FindYourOrder.as_view(), name = "find_your_order"),
    path("display_basket/", views.DisplayBasket.as_view(), name = "display_basket"),
    path("add_category/", views.ADD_Category.as_view(), name = "add_category"),
    path("display_category/",  views.DisplayCategory.as_view(), name = "display_category"),
    path("display_unknown_category/", views.DisplayUnknownCategory.as_view(), name = "display_unknown_category"),
    path("display_current_category/<str:cat_name>/", views.DisplayCurrentCategory.as_view(), name = "display_current_category"),
    path("payment_action/", views.PaymentAction.as_view(), name = "payment_action"),
    path('remove_from_list/<int:item_id>/', views.remove_from_list, name='remove_from_list'),
    path("wallet_page/", views.WalletPage.as_view(), name="wallet_page"), 
    ]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path("folder_market/", include("folder_market.urls")),
    path('auth_market/', include("auth_market.urls")),
    path('captcha/', include('captcha.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] 

handler404 = "folder_market.views.handler404"
handler500 = "folder_market.views.handler500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

folder_market/forms.py
from django import forms
from .models_for import Item_info, Salesman_info, Category
from captcha.fields import CaptchaField

class addItem(forms.ModelForm):
    imagine_file = forms.FileField(required=False)
    product_description = forms.CharField(required=False, widget= forms.Textarea())
    category = forms.ModelChoiceField(queryset= Category.objects.all(), to_field_name='category', required=False)
    class Meta:
        model = Item_info
        fields = ['name', 'price', 'imagine_file', 'product_description', 'category']

class ChangeItem(forms.ModelForm):
    imagine_file = forms.FileField(required=False)
    product_description = forms.CharField(required=False, widget= forms.Textarea())
    class Meta:
        model = Item_info
        fields = ["price", 'product_description', 'imagine_file']
        
class SearchData(forms.Form):
    desired_item = forms.CharField(required=False)
    
class CreateSalesmans(forms.ModelForm):
    username = forms.EmailField(required=False)
    rating = forms.FloatField(required=False)  
    class Meta:
        model = Salesman_info
        exclude = ["validator_user", "card_number"]

class OnlyForSubmit(forms.Form):
    submit = forms.CharField(required=False, widget=forms.HiddenInput())

class OnlyForDelete(forms.Form):
    delete = forms.CharField(required=False, widget=forms.HiddenInput())
    
    
class CreateCategory(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"
        
class AddCard(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Salesman_info
        fields = ["card_number"]

folder_market/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, FormView
from .models_for import (Item_info, Salesman_info, 
                         RatingStorage, BasketScope, Category)
from .forms import (addItem, SearchData, CreateSalesmans, OnlyForSubmit, OnlyForDelete, 
                    CreateCategory, AddCard, ChangeItem)
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.cache import cache_page
from django.http import HttpResponse
from thefuzz import fuzz
from django.contrib import messages
from .system_rating import recommendation_func
from .system_statistics import display_statistics
from collections import deque
from .basket_for import add_item, remove_item, remove_card, remove_item_info
from .filter_system import if_word_real, make_suggestion
from .check_category import check_caregory, google_search_link
from django.db.models import Sum


class RedirectIndex(View):
    def get(self, request):
        return redirect("/folder_market/1")

class Index(ListView):
    model = RatingStorage
    template_name = "folder_market/index.html"
    paginate_by = 5
    context_object_name = "display_page"
    
    def get_queryset(self):
        ratings_storage = super().get_queryset()
        ratings_storage = ratings_storage.filter(unique_user = self.request.user.username).select_related("id_connector")
        display_page = deque()
        for rating_storage in ratings_storage:
            if rating_storage.rating_storage > recommendation_func(self.request.user.username):
               display_page.appendleft([rating_storage.id_connector])
            else:
                display_page.append([rating_storage.id_connector])
        return list(display_page)  
    
class DashboardItems(FormView):
    form_class = addItem
    template_name = "folder_market/dashboard_items.html"
    context_object_name = "form"
    
    def form_valid(self, form):
        username_for = self.request.user.username
        form = addItem(self.request.POST, self.request.FILES)
        for_reuse = Salesman_info.objects.filter(validator_user=username_for)
        if form.is_valid():
            if for_reuse.exists():
                mapping_data = form.cleaned_data["name"]
                for salesman_info in Salesman_info.objects.all():
                    if salesman_info.validator_user == username_for:
                        try:
                            data_use = form.save(commit=False)
                            data_use.salesman = username_for
                            if check_caregory(mapping_data) == True:    
                                data_use.save()
                            else:
                                data_use.category = None
                                data_use.save()
                                return redirect("/folder_market/")
                        except:
                            messages.error(self.request, "Error1")
            else:
                try:
                    form.save()
                    return redirect("/folder_market/")
                except:
                    messages.error(self.request, "Error2")
            return redirect("/folder_market/")

@method_decorator(login_required, name='dispatch')    
class UpdateItem(FormView):
    template_name = "folder_market/update_item.html"
    form_class = ChangeItem
    form1_class = OnlyForDelete
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class()
        context["form1"] = self.form1_class()
        return context
    
    def post(self, request, *args, **kwargs):
        check_item = self.kwargs["check_item"]
        username_for = self.request.user.username
        change_item = Item_info.objects.get(name=check_item)
        form = ChangeItem(self.request.POST, self.request.FILES, instance=change_item)
        form1 = OnlyForDelete(self.request.POST)
        if self.request.method == "POST":
            if "form-update" in self.request.POST:
                if change_item.salesman == username_for:
                    if form.is_valid():
                        mapping_data1 = form.cleaned_data["price"]
                        mapping_data2 = form.cleaned_data["product_description"]
                        mapping_data3 = form.cleaned_data["imagine_file"]
                        try:
                            change_form = form.save(commit=False)
                            change_form.price = mapping_data1
                            change_form.product_description = mapping_data2
                            change_form.imagine_file = mapping_data3
                            change_form.save()
                            return redirect("/folder_market/")
                        except Exception as e:
                            return e
                    
                    else:
                        messages.error(self.request, "Error")
                else:
                    return HttpResponse("You haven't access to page")
            if "form-delete" in self.request.POST:
                if change_item.salesman == username_for:
                    if form1.is_valid():
                        remove_item_info(check_item)
                        return redirect("/folder_market/")
                    else:
                        messages.error(self.request, "Error1")
                else:
                    return HttpResponse("You haven't access to page")

                
@method_decorator(login_required, name='dispatch')   
class DashboardSalesmans(ListView):
    model = Salesman_info
    template_name = "folder_market/dashboard_salesmans.html"
    context_object_name = "data_items"
        
    def get_queryset(self):
        try:
            data_items = super().get_queryset()
            data_items = data_items.get(validator_user=self.request.user.username)
            return data_items
        except Salesman_info.DoesNotExist:
            data_items = None

@method_decorator(login_required, name='dispatch')   
class StartTrade(FormView):
    template_name = "folder_market/start_trade.html"
    form_class = CreateSalesmans
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username_for = self.request.user.username
        check = Salesman_info.objects.filter(validator_user=username_for).exists()
        context["username_for"] = username_for
        context["check"] = check
        context["display_statistics"] = display_statistics(self.request)
        return context
    
    def form_valid(self, form):
        username_for = self.request.user.username
        check = Salesman_info.objects.filter(validator_user=username_for).exists()
        if check:
            messages.error(self.request, "Error1")
        else:
            salesman = form.save(commit=False)
            salesman.validator_user = username_for
            salesman.save()
            return redirect("/folder_market/dashboard_salesmans/")

class SearchItem(FormView):
    template_name = "folder_market/search.html"
    form_class = SearchData
    def post(self, request, *args, **kwargs):
        form = SearchData(self.request.POST)
        context = {"form": form}
        if form.is_valid():
            desired_input = form.cleaned_data["desired_item"]
            container_ability = Item_info.objects.all().values("item_id", "name", "price")
            desired_ratio = 55
            desired_list = []
            for item in container_ability:
                ratio = fuzz.ratio(desired_input, item["name"])
                if desired_ratio <= ratio:
                    desired_list.append(item)            
            if desired_list == []:
                messages.error(request, google_search_link(desired_input))
            else:
                context = {"form": form, "desired_list": desired_list}
                return render(request, "folder_market/search.html", context)        
        return render(request, "folder_market/search.html", context)   


class FindYourOrder(FormView):
    template_name = "folder_market/find_your_order.html"
    form_class = CreateSalesmans
    form1_class = OnlyForSubmit
    form2_class = OnlyForDelete
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class()
        context["form1"] = self.form1_class()
        context["form2"] = self.form2_class()
        id_product = self.kwargs["id_product"]
        context["item_id"] = Item_info.objects.get(item_id = id_product)
        return context
    
    def post(self, request, *args, **kwargs):
        id_product = self.kwargs["id_product"]
        item_id = Item_info.objects.get(item_id = id_product)
        try:
            salesman_info = Salesman_info.objects.get(validator_user=item_id.salesman)
        except Salesman_info.DoesNotExist:
            salesman_info = None
        form = CreateSalesmans(request.POST, instance=salesman_info)
        form1 = OnlyForSubmit(request.POST)
        form2 = OnlyForDelete(request.POST)
        if request.method == "POST":
            if "form-submit" in request.POST:
                if form.is_valid(): 
                    mapping_data = form.cleaned_data["rating"]
                    if request.user.is_authenticated:
                        if RatingStorage.objects.filter(id_connector=item_id, unique_user=request.user.username).exists():
                            messages.error(request, "You could evaluate page only once")
                        else:
                            if salesman_info != None:
                                RatingStorage.objects.create(rating_storage = salesman_info.rating, salesman_connector = salesman_info, 

folder_market/templates/folder_market/dashboard_salesmans.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Salesmans raiting</title>
	{% load static %} 
  	{% load bootstrap5 %}
  	{% bootstrap_css %}
  	{% bootstrap_javascript %}
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-8">
                            {% if data_items.username != None %}
                            <p class="fw-bolder">
                                {{ data_items.username }}
                            </p>
                            {% else %}
                            <p>To start create trading account</p>
                            {% endif %}
                        </div>
                        {% if data_items.username != None %}
                        <div class="col-sm-4">
                            <a href="{% url 'folder_market:wallet_page' %}" title="third_link">
                            <img
                                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWz93g9V8xIS1yApm62ez9QTwVmNHxF-I5TZP8qDJn8HNlzfDh2hf0ZiYrhapRO6BV9TA&usqp=CAU"
                                class="me-2"
                                height="20"
                                alt="MDB Logo"
                                loading="lazy"
                            />
                            </a>
                        </div>
                        {% endif %}
                    </div>
                    <div class="row">
                    <div class="col-sm-8">
                        <p class="fw-lighter">
                            {{ data_items.validator_user }}
                        </p>
                    </div>
                    <div class="col-sm-4">
                            <a href="{% url 'folder_market:display_basket' %}" title="first_click">
                            <img
                                src="https://cdn-icons-png.flaticon.com/512/3721/3721818.png"
                                class="me-2"
                                height="20"
                                alt="MDB Logo"
                                loading="lazy"
                            />
                            </a>
                        </div>
                    </div>
                    <div class="row">
                    <div class="col-sm-8">
                        <p class="fw-normal">
                            {{ data_items.rating }}
                        </p>
                    </div>
                    <div class="col-sm-4">
                            <a href="{% url 'folder_market:start_trade' %}" title="second_link">
                            <img
                                src="https://w7.pngwing.com/pngs/998/466/png-transparent-computer-icons-people-logo-logo-black-silhouette-thumbnail.png"
                                class="me-2"
                                height="20"
                                alt="MDB Logo"
                                loading="lazy"
                            />
                            </a>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-8">
                            <form action="{% url 'folder_market:redirect_index' %}">
                                <button type="submit" id = "go_back" class="btn btn-light" data-mdb-ripple-color="dark">Go back</button>
                            </form>
                        </div>
                        <div class="col-sm-4">
                            <p class="fw-bolder">
                                Statistic
                            </p>
                        </div>
                    </div>
                </div>
        </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

folder_market/templates/folder_market/display_basket.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Your basket</title>
	{% load static %} 
  	{% load bootstrap5 %}
  	{% bootstrap_css %}
  	{% bootstrap_javascript %}
</head>
<body>
  <div class="container h-100 py-5">
  	<div class="row d-flex justify-content-center align-items-center h-100">
  	<div class="d-flex justify-content-between align-items-center mb-4">
  		<div class="col-10">
  		<div class="col-10">
          <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
           <a class="navbar-brand" href="{% url 'folder_market:redirect_index' %}" title="first_url">Return</a>
        </div>
    	</div>
    </div>
	</div>
  	{% for data in list_for_basket %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
  	{% for d in data %}
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">
        <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                {% if d.0.imagine_file == None %}
                <img
                  src="https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg"
                  class="img-fluid rounded-3" alt="Cotton T-shirt">
                  {% else %}
                  <img
                  src="{{d.0.imagine_file.url}}"
                  class="img-fluid rounded-3" alt="Cotton T-shirt">
                  {% endif %}
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">{{d.0.name}}</p>
                <p><span class="text-muted">Salesman: </span> 
                	{% if d.0.salesman == None %}
          				Anonymous  user 
          			{% else %}
          			{{ d.0.salesman }}
          			{% endif %}
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0">${{d.0.price}}</h5>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <button type="button" id = "actionField" class="btn-close" data-bs-dismiss="alert" aria-label="Close" onclick="remove_from_list({{ d.0.item_id }})">
                <span aria-hidden="true"></span></button>
              </div>  
            </div>
          </div>
        </div>    
      </div>
    </div>
    {% endfor %}
  </div>
    {% endfor %}
    <script type="text/javascript">
       function remove_from_list(item_id) {
        var request = new XMLHttpRequest();
        request.open('GET', '/folder_market/remove_from_list/' + item_id + '/' , true);
        request.onreadystatechange = function () {
            if (request.readyState === 4) {
                if (request.status === 200) {
                    location.reload();
                } else {
                    alert("Error: " + request.statusText);
                }
            }
        };
        request.send();
    }
    </script>
    <div class="card">
    <div class="card-body">
    <button type="button" id = "button_submit" class="btn btn-warning btn-block btn-lg" onclick="window.location.href='{% url 'folder_market:payment_action' %}'">
        Proceed to Pay
    </button>
</div>

  </div>
  </div>
</body>
</html>

folder_market/templates/folder_market/display_category.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>List of categories</title>
	{% load static %} 
  	{% load bootstrap5 %}
  	{% bootstrap_css %}
  	{% bootstrap_javascript %}
</head>
<body>
<table class="table align-middle">
  <thead>
    <tr>
      <th scope="col">Category</th>
      <th scope="col">List of items</th>
    </tr>
  </thead>
  <tbody>
  {% for category in get_category %}
    <tr>
      <td>{{category.category}}</td>
      <td><a href="{% url 'folder_market:display_current_category' cat_name=category.category %}">url of data</a></td>
    </tr>
   {% endfor %}
    <tr>
    	<td>Unknown</td>
    	<td><a href="{% url 'folder_market:display_unknown_category'%}">url of data</a></td>
    </tr>
  </tbody>

</table>
</body>
</html>

folder_market/templates/folder_market/display_current_category.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	{% load static %} 
  	{% load bootstrap5 %}
  	{% bootstrap_css %}
  	{% bootstrap_javascript %}
</head>
<body>
	{% if item_category %}
	<table class="table align-middle">
  	<thead>
    <tr>
      <th scope="col">Category</th>
      <th scope="col">List of items</th>
    </tr>
  	</thead>
  <tbody>
  {% for item in item_category %}
    <tr>
      <td>{{item.name}}</td>
      <td><a href="{% url 'folder_market:find_your_order' id_product=item.item_id %}">url of data</a></td>
    </tr>
   {% endfor %}
  </tbody>
</table>
	{% else %}
	<p>Sorry no data</p>
	<p>For more information and questions:</p>
	<h3>asksomething@gmail.com</h3>
	{% endif %}
</body>
</html>

folder_market/templates/folder_market/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}Items list</title>
  {% load static %} 
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'folder_market:search_item' %}">
      <img
        src="https://cdn-icons-png.flaticon.com/512/3917/3917132.png"
        class="me-2"
        height="20"
        alt="MDB Logo"
        loading="lazy"
      />
      <small>Search</small>
    </a>
    <a class="navbar-brand" href="{% url 'folder_market:dashboard_salesmans' %}">
      <img
        src="https://static.thenounproject.com/png/4038155-200.png"
        class="me-2"
        height="20"
        alt="MDB Logo"
        loading="lazy"
      />
      <small>Account</small>
    </a>
      <a class="navbar-brand" href="{% url 'folder_market:dashboard_items' %}">
        <img
        src="https://static.thenounproject.com/png/4410346-200.png"
        class="me-2"
        height="20"
        alt="MDB Logo"
        loading="lazy"
        />
        <small>Create order</small>
      </a>
      <a class="navbar-brand" href="{% url 'folder_market:display_category' %}">
      <img
        src="https://icon-library.com/images/icon-categories/icon-categories-8.jpg"
        class="me-2"
        height="20"
        alt="MDB Logo"
        loading="lazy"
      />
      <small>Categories</small>
      </a>
      <div class="dropdown">
      <a class="navbar-brand" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
        <img
        src="https://cdn-icons-png.flaticon.com/512/126/126472.png"
        class="me-2"
        height="20"
        alt="MDB Logo"
        loading="lazy"
        />
      <small>Settings</small>
      </a>

      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <li><a class="dropdown-item" href="{% url 'auth_market:change_username' %}">
          Change username
        </a></li>
        <li><a class="dropdown-item" href="{% url 'auth_market:change_info' %}">
          Change password
        </a></li>
        <li><a class="dropdown-item" href="{% url 'auth_market:change_email' %}">
          Change email
        </a></li>
        <li><a class="dropdown-item" href="{% url 'auth_market:display_user_account' %}">
          Account data
        </a></li>
        {% if request.user.is_staff %}
        <li><a class="dropdown-item" href="{% url 'folder_market:add_category' %}">
          Add category
        </a></li>
        {% endif %}
      </ul>
      <a class="navbar-brand" href="{% url 'auth_market:log_out' %}">
      <img
        src="https://w7.pngwing.com/pngs/475/85/png-transparent-computer-icons-logout-angle-text-black-thumbnail.png"
        class="me-2"
        height="20"
        alt="MDB Logo"
        loading="lazy"
        />
      <small>Log out</small>
      </a>
</div>
</nav>
<table class="table align-middle mb-0 bg-white">
  <thead class="bg-light">
    <tr>
      <th scope="col">Description</th>
      <th scope="col">Dop info</th>
    </tr>
  </thead>
    {% for item in display_page %}
    <tr>
      <td class="table-secondary">
        <div class="d-flex align-items-center">
          <span class="badge badge-pill badge-dark">{{item.0.item_id}}</span>
         <div class="ms-3">
            <p class="fw-bold mb-1">
              {{ item.0.name }}
            </p>
            <p class="text-muted mb-0">
              {{ item.0.price }}
            </p>
            <p class="text-muted mb-0">
              {% if item.0.category != None %}
                {{item.0.category}}
              {% else %}
                No category
              {% endif %}
            </p>
          </div>
          </div>
      </td>
      <td class="table-secondary">
      <div class="ms-3">
      <p class="fw-bold mb-1">
        {% if item.0.salesman == None %}
          Anonymous  user 
          {% else %}
          {{ item.0.salesman }}
          {% endif %}
      </p>
      <p class="text-muted mb-0">
        {{item.0.data_creation}}
      </p>
      </div>
      </td>
    </tr>
    {% endfor %}
</table>
{% if is_paginated %}
<div class='pagination justify-content-center'>
  <nav aria-label="Page navigation example">
    <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href='{% url "folder_market:index" page=page_obj.previous_page_number %}'>Previous </a>
    </li>
    {% endif %}

    <li class="page-item">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </li>

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href='{% url "folder_market:index" page=page_obj.next_page_number  %}' > Next</a>
    </li>
    {% endif %}
  </ul>
  </nav>
  </div>
{% endif %}
</body>
</html>

folder_market/templates/folder_market/search.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Search</title>
	{% load static %} 
  	{% load bootstrap5 %}
  	{% bootstrap_css %}
  	{% bootstrap_javascript %}
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
</head>
<body>
<div class="container">
<form action="" method="POST">
  {% csrf_token %}
  <div class="input-group" style="width: 600px;">
      <span class="input-group-text"><i class="fab fa-google"></i></span>
      <input type="text" id = "text_input" class="form-control" name="desired_item" placeholder="Search for an item">
      <button class="btn btn-outline-secondary" id= "button_submit" type="submit">
      	<i class="fa fa-home" aria-hidden="true"></i>
      </button>
	</div>
</form>
{% block content %}
{% if desired_list != None %}
<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
<table class="table">
<tbody>
{% for i in desired_list %}
	<tr>
	<td><a href="{% url 'folder_market:find_your_order' id_product=i.item_id %}">{{i.name}}</a></td>
	</tr>
{% endfor %} 
</tbody>
	{% if messages %}
	{% for message in messages %}
		{{message}}
	{% endfor %}
	{% endif %}
</table>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
	<span aria-hidden="true"></span>
</button>
</div>
{% endif %}

{% if messages %}
<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
	{% for message in messages %}
		<a href="{{message}}" target="_blank">{{message}}</a>
	{% endfor %}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
	<span aria-hidden="true"></span>
	</button>
</div>
{% endif %}
<a class="navbar-brand" href="{% url 'folder_market:redirect_index' %}">  
	<img
        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCyCK0EShSSwJp7g0zlTx7NX0PfpuqgnAWQotpoktmag&s"
        class="me-2"
        height="20"
        alt="MDB Logo"
        loading="lazy"
      /><small>Return</small></a>

{% endblock %}
</body>
</html>