auth_market/urls.py
from django.urls import path
from . import views
app_name = "auth_market"
urlpatterns = [
    path("login/", views.login_user, name="login_user"),
    path("log_out/", views.log_out, name = "log_out"),
    path('register/', views.register, name='register'),
    path("change_info/", views.change_info, name = "change_info"),
    path("change_username/", views.change_username, name = "change_username"),
    path("change_email/", views.change_email, name = "change_email"),
    path("send_secret_key/", views.send_secret_key, name = "send_secret_key"),
    path("display_user_account/", views.display_user_account, name = "display_user_account")
    ]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path("folder_market/", include("folder_market.urls")),
    path('auth_market/', include("auth_market.urls")),
    path('captcha/', include('captcha.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] 

handler404 = "folder_market.views.handler404"
handler500 = "folder_market.views.handler500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

auth_market/models.py
from django.db import models

auth_market/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin
from captcha.fields import CaptchaField


class RegisterForm(UserCreationForm, forms.Form):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    captcha = CaptchaField()
    class Meta:
        model = User
        fields =  ("username", "password1", "password2")

class FormChange(PasswordChangeForm):
    verification_field = forms.CharField(required=False)
    class Meta:
        model = User
        fields = []
        
class ChangeUsername(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username',)
        
class Change_Email(forms.ModelForm):
    verification_field = forms.CharField(required=False)
    class Meta:
        model = User
        fields = ("email",)
        
class CustomUserAdmin(UserAdmin):
    def get_form(self, request, obj = None,**kwargs):
        form = super().get_form(request, obj, **kwargs)
        is_superuser = request.user.is_superuser
        restriction_field = set()
        if not is_superuser:
            restriction_field |= {
                "is_superuser",
                "user_permissions",
                }
        if (not is_superuser
            and obj is not None
            and obj == request.user
                ):
            restriction_field |= {
                'is_staff',
                'is_superuser',
                'groups',
                'user_permissions',
                }
        
        for r in restriction_field:
            if r in form.base_fields:
                form.base_fields[r].disabled = True
        def has_change_permission(self, request, obj=None):
            return False
        def has_delete_permission(self, request, obj=None):
            return False
        return form

auth_market/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import (RegisterForm, FormChange, ChangeUsername, 
                    Change_Email)
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from folder_market.models_for import Salesman_info, Item_info, RatingStorage
from django.core.mail import send_mail
from django.contrib.auth import update_session_auth_hash
from folder_market.sensitive_ignore import Email_one_ignore
from django.http import HttpResponse
import pyotp
import urllib.parse

totp = pyotp.TOTP("base32secret3232", interval=300)


def register(request):
    form = RegisterForm(request.POST)
    context = {"form": form}
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(request.GET.get('next', reverse("folder_market:redirect_index")))
        else:
            messages.error(request, form.errors)
    return render(request, "auth_market/register.html", context)

def login_user(request):
    form = AuthenticationForm(data = request.POST)
    context = {"form": form}
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(request.GET.get('next', reverse("folder_market:redirect_index")))
        else:
            messages.error(request, "Error")
    return render(request, "auth_market/login.html", context)

@login_required
def change_info(request):
    form = FormChange(request.user, request.POST)
    
    if request.user.email == "":
        return redirect("/auth_market/change_email/")
    
    context = {"form": form}
    if request.method == "POST":
        if form.is_valid():
            mapping_data = form.cleaned_data["verification_field"]
            if totp.verify(mapping_data):
                form.save()
                update_session_auth_hash(request, form.user)
                send_email(request, "You have changed your password")
                return redirect(request.GET.get('next', reverse("folder_market:redirect_index")))
            else:
                messages.error(request, "Failed verification")
        else:
            messages.error(request, form.errors)
    return render(request, "auth_market/change_info.html", context)

@login_required
def change_username(request):
    form = ChangeUsername(request.POST, instance=request.user)
    old_username = request.user.username
    context = {"form": form}
    if request.method == "POST":
        if form.is_valid():
            mapping_data = form.cleaned_data["username"]
            for salesman_info in Salesman_info.objects.filter(validator_user= old_username):    
                salesman_info.validator_user = mapping_data
                salesman_info.save()
            for item_info in Item_info.objects.filter(salesman= old_username):
                item_info.salesman = mapping_data
                item_info.save()
            for rating_info in RatingStorage.objects.filter(unique_user= old_username):
                rating_info.unique_user = mapping_data
                rating_info.save()
            form.save()
            send_email(request, "You have changed your username")
            return redirect(request.GET.get('next', reverse("folder_market:redirect_index")))
        else:
            messages.error(request, "Error")
    return render(request, "auth_market/change_username.html", context)

def change_email(request):
    form = Change_Email(request.POST, instance=request.user)
    context = {"form": form, "email_check": request.user.email}
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(request.GET.get('next', reverse("folder_market:redirect_index")))
        else:
            messages.error(request, "Error")
    return render(request, "auth_market/change_email.html", context)

@login_required
def display_user_account(request):
    context = {
        "data1": request.user.username,
        "data2": request.user.email, 
        "data3": request.user.date_joined
        }
    return render(request, "auth_market/display_user_account.html", context)

def send_email(request, body):
    send_mail(
        'Notification',
        str(body),
        Email_one_ignore,
        [request.user.email],
        fail_silently=False,
    )
    
def send_secret_key(request):
    email = urllib.parse.unquote(request.GET.get('email', ''))
    send_mail("Submit action", totp.now(), Email_one_ignore, [email], fail_silently=False,)
    return HttpResponse("Sending", 200)

def log_out(request):
    logout(request)
    return redirect("/auth_market/login")


                
        

auth_market/templates/auth_market/change_email.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Change email</title>
	{% load static %}
	{% load bootstrap5 %}
	{% bootstrap_css %}
	{% bootstrap_javascript %} 
</head>
<body>
<section class="vh-100" style="background-color: #2779e2;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-9">
        {% if email_check == "" %}
        <h1 class="text-white mb-4">Create e-mail</h1>
        {% else %}
        <h1 class="text-white mb-4">Change e-mail</h1>
        {% endif %}
        <div class="card" style="border-radius: 15px;">
          <div class="card-body">
          	<form action="" method="POST">
          	{% csrf_token %}
            <div class="row align-items-center pt-4 pb-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">New email</h6>

              </div>
              <div class="col-md-9 pe-5">
                {{form.email}}
              </div>
            </div>
            <hr class="mx-n3">
            <div class="px-5 py-4">
              <button type="submit" class="btn btn-primary btn-lg">Submit</button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% if messages %}
{{form.error}}
{% for message in messages %}
{{message}}
{% endfor %}
{% endif %} 
</body>
</html>

auth_market/templates/auth_market/change_info.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Change password</title>
  {% load static %}
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %} 
</head>
<body>
<section class="vh-100 gradient-custom" style="background-image: url('https://mdbootstrap.com/img/new/textures/full/171.jpg');">

  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Change password</h2>
              <p class="text-white-50 mb-5">Please enter username and password!</p>
              <form action="" method="POST">
              {% csrf_token %}
              {{form.username}}
              <div class="form-outline form-white mb-4">
                <label class="form-label" for="typeEmailX">Welcome, {{request.user.username}}</label>
              </div>

              <div class="form-outline form-white mb-4">
                {{form.old_password }}
                <label class="form-label" for="typePasswordX">Password0</label>
              </div>

              <div class="form-outline form-white mb-4">
                {{form.new_password1}} 
                <label class="form-label" for="typePasswordX">Password1</label>
              </div>
              <div class="form-outline form-white mb-4">
                {{form.new_password2}} 
                <label class="form-label" for="typePasswordX">Password1</label>
              </div>
              <div class="form-outline form-white mb-4">
                {{form.verification_field}} 
                <label class="form-label" for="typePasswordX">Verification</label>
              </div>
              <p class="small mb-5 pb-lg-2"><a class="text-white-50" onclick="send_secret_key()">Verification</a></p>

              <button class="btn btn-outline-light btn-lg px-5" type="submit">Submit</button>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  <script type="text/javascript">
       function send_secret_key() {
        var request = new XMLHttpRequest();
        var url = '/auth_market/send_secret_key/?email=' + encodeURIComponent('{{ request.user.email }}');
        request.open('GET', url, true);
        request.onreadystatechange = function () {
            if (request.readyState === 4) {
                if (request.status === 200) {
                    alert("Message have been sent")
                } else {
                    alert("Error: " + request.statusText);
                }
            }
        };
        request.send();
    }
</script>
{% if messages %}
{{form.error}}
{% for message in messages %}
{{message}}
{% endfor %}
{% endif %} 
</body>
</html>

auth_market/templates/auth_market/change_username.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	{% load static %} 
  	{% load bootstrap5 %}
  	{% bootstrap_css %}
  	{% bootstrap_javascript %}
</head>
<body>
<div class="container">
<form method="POST">
	{% csrf_token %}
	<div class="input-group mb-3" style="width: 300px">
  	<button class="btn btn-outline-primary" type="button" id="button-addon1" data-mdb-ripple-color="dark">
    Button
  	</button>
  	{{form.username}}
	</div>
</form>
</div>
</body>
</html>

auth_market/templates/auth_market/display_user_account.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	{% load static %}
  	{% load bootstrap5 %}
  	{% bootstrap_css %}
  	{% bootstrap_javascript %} 
</head>
<body>
<div class="container d-flex justify-content-center align-items-center">         
      <div class="custom-container">
    <div class="card">
      <div class="mt-5 text-center">
        <h4 class="mb-0">{{data1}}</h4>
        <span class="text-muted d-block mb-2">{{data2}}</span>
        <div class="d-flex justify-content-between align-items-center mt-4 px-4">
          <div class="stats">
            <h6 class="mb-0">Joined</h6>
            <span>{{data3}}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

auth_market/templates/auth_market/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login page</title>
  {% load static %} 
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="https://play-lh.googleusercontent.com/XHmjyKPZCTadt1ZVFfZ6jYDCg3IgLjE35AlcobKTvoiKiatXNRJobOzPRndOXNtEOr8"
          class="img-fluid" alt="Sample image">
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <form action="" method="POST">
        	{% csrf_token %}
          <div class="form-outline mb-4">
            {{form.username}}
            <label class="form-label" for="form3Example3">Enter username</label>
          </div>

          <div class="form-outline mb-3">
            {{form.password}}
            <label class="form-label" for="form3Example4">Password</label>
          </div>

          <div class="d-flex justify-content-between align-items-center">
            <a href="{% url 'auth_market:change_info' %}" class="text-body">Forgot password?</a>
          </div>

          <div class="text-center text-lg-start mt-4 pt-2">
            <button type="submit" name="login" class="btn btn-primary btn-lg"
  			style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
            <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'auth_market:register' %}"
                class="link-danger">Register</a></p>
          </div>

        </form>
      </div>
    </div>
  </div>
  <div
    class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
    <div class="text-white mb-3 mb-md-0">
      Copyright © 2023. All rights reserved.
    </div>
</section>
</body>
</html>

auth_market/templates/auth_market/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Register</title>
	{% load static %} 
  	{% load bootstrap5 %}
  	{% bootstrap_css %}
  	{% bootstrap_javascript %}
</head>
<body>
<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                <form class="mx-1 mx-md-4" action="" method="POST">
                	{% csrf_token %}

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{form.username}}
                      <label class="form-label" for="form3Example1c">Your Name</label>
                    </div>
                  </div>

                

                <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{form.password1}}
                      <label class="form-label" for="form3Example4c">Password</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      {{form.password2}}
                      <label class="form-label" for="form3Example4cd">Repeat</label>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    {{form.captcha}}
                    <button type="submit" class="btn btn-primary btn-lg">Register</button>
                    
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% if messages %}
{{form.error}}
{% for message in messages %}
{{message}}
{% endfor %}
{% endif %} 
</body>
</html>